//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comodity
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CretedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> NetUnitPrice { get; set; }
        public Nullable<decimal> VatRate { get; set; }
        public Nullable<int> StorageSizeId { get; set; }
        public Nullable<int> brandId { get; set; }
        public Nullable<int> CommodityCategoryId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual CommodityCategory CommodityCategory { get; set; }
        public virtual storageSizes storageSizes { get; set; }
    }
}
