//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PeselNumber { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CretedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int AddressId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int warehouseId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual employeeType employeeType { get; set; }
        public virtual warhouse warhouse { get; set; }
    }
}
