//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeeType()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CretedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee { get; set; }
    }
}
