//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfService.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMABEntities : DbContext
    {
        public PMABEntities()
            : base("name=PMABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<CommodityCategory> CommodityCategory { get; set; }
        public virtual DbSet<Comodity> Comodity { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employeeType> employeeType { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<storageSizes> storageSizes { get; set; }
        public virtual DbSet<storageStatus> storageStatus { get; set; }
        public virtual DbSet<warhouse> warhouse { get; set; }
    }
}
