//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class storageSizes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public storageSizes()
        {
            this.Comodity = new HashSet<Comodity>();
            this.storage = new HashSet<storage>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CretedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Name { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> z { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comodity> Comodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storage> storage { get; set; }
    }
}
