//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CretedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> StorageStatusId { get; set; }
        public Nullable<int> StorageSizeId { get; set; }
    
        public virtual storageStatus storageStatus { get; set; }
        public virtual storageSizes storageSizes { get; set; }
    }
}
